DROP TABLE IF EXISTS samples;

CREATE TABLE samples (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         content VARCHAR(256) NOT NULL
);

CREATE TABLE tasks (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         title VARCHAR(256) NOT NULL
);